name: Auto Commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 6,9,12,15,18 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          cat > LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "erickchandra718@gmail.com"
          git config --local user.name "erickchann"
          git add -A
          git commit -m "Helloo"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}